spring:
  application:
    name: Diploma
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5433/itmo_diploma?charSet=UTF-8
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true