spring:
  application:
    name: Diploma
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"


  datasource:
    url: jdbc:postgresql://localhost:5433/itmo_diploma
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true